image: node:10.15.3
build_and_test_step: &build_and_test_step
  - step:
      name: Build and Test
      caches:
        - node
      script:
        - npm install
        - npm run test
create_release_step: &create_release_step
  - step:
      name: Create release
      script:
        - apt-get update
        - apt-get install -y zip
        - npm install
        - echo "Zipping bundle..."
        - zip -r application.zip *
      artifacts:
        - application.zip
create_release_step_manual: &create_release_step_manual
  - step:
      name: Create release
      trigger: manual
      script:
        - apt-get update
        - apt-get install -y zip
        - npm install
        - echo "Zipping bundle..."
        - zip -r application.zip *
      artifacts:
        - application.zip
push_to_s3_step: &push_to_s3_step
  - step:
      name: Pushing to S3
      script:
        - pipe: atlassian/aws-elasticbeanstalk-deploy:0.2.5
          variables:
            AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
            AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
            ZIP_FILE: 'application.zip'
            S3_BUCKET: 'elasticbeanstalk-us-east-2-350152003452'
            APPLICATION_NAME: 'lendsqr-backend'
            VERSION_LABEL: 'lendsqr-backend-release-$BITBUCKET_BUILD_NUMBER'
            COMMAND: 'upload-only'
            WAIT: 'true'
deploy_to_test_step: &deploy_to_test_step
  - step:
      name: Deploy to test
      deployment: test
      trigger: manual
      script:
        - echo "Deploying to test environment"
        - pipe: atlassian/aws-elasticbeanstalk-deploy:0.2.5
          variables:
            AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
            AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
            ZIP_FILE: 'application.zip'
            S3_BUCKET: 'elasticbeanstalk-us-east-2-350152003452'
            APPLICATION_NAME: 'lendsqr-backend'
            ENVIRONMENT_NAME: 'test-lendsqr-backend'
            VERSION_LABEL: 'lendsqr-backend-release-$BITBUCKET_BUILD_NUMBER'
            COMMAND: 'deploy-only'
            WAIT: 'true'
deploy_to_staging_step: &deploy_to_staging_step
  - step:
      name: Deploy to staging
      deployment: staging
      script:
        - echo "Deploying to staging environment"
        - pipe: atlassian/aws-elasticbeanstalk-deploy:0.2.5
          variables:
            AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
            AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
            ZIP_FILE: 'application.zip'
            S3_BUCKET: 'elasticbeanstalk-us-east-2-350152003452'
            APPLICATION_NAME: 'lendsqr-backend'
            ENVIRONMENT_NAME: 'staging-lendsqr-backend'
            VERSION_LABEL: 'lendsqr-backend-release-$BITBUCKET_BUILD_NUMBER'
            COMMAND: 'deploy-only'
            WAIT: 'true'
deploy_to_live_step: &deploy_to_live_step
  - step:
      name: Deploy to live
      deployment: production
      trigger: manual
      script:
        - echo "Deploying to live environment"
        - pipe: atlassian/aws-elasticbeanstalk-deploy:0.2.5
          variables:
            AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
            AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
            ZIP_FILE: 'application.zip'
            S3_BUCKET: 'elasticbeanstalk-us-east-2-350152003452'
            APPLICATION_NAME: 'lendsqr-backend'
            ENVIRONMENT_NAME: 'live-lendsqr-backend'
            VERSION_LABEL: 'lendsqr-backend-release-$BITBUCKET_BUILD_NUMBER'
            COMMAND: 'deploy-only'
            WAIT: 'true'
pipelines:
  default:
    - <<: *build_and_test_step
  pull-requests:
    '**':
      - <<: *build_and_test_step
  branches:
    feature/*:
      - <<: *build_and_test_step
      - <<: *create_release_step_manual
      - <<: *push_to_s3_step
      - <<: *deploy_to_test_step
    bugfix/*:
      - <<: *build_and_test_step
      - <<: *create_release_step_manual
      - <<: *push_to_s3_step
      - <<: *deploy_to_test_step
    develop:
      - <<: *build_and_test_step
      - <<: *create_release_step
      - <<: *push_to_s3_step
      - <<: *deploy_to_staging_step
    master:
      - <<: *build_and_test_step
      - <<: *create_release_step
      - <<: *push_to_s3_step
      - <<: *deploy_to_live_step
